use_frameworks!

platform :ios, '8.0'

target 'GMNoNetworkAlert_Example' do
  pod 'GMNoNetworkAlert', :path => '../'

  target 'GMNoNetworkAlert_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
